### ISSUE TITLE
Code snippets hard to read

### ISSUE THREAD

**Issue by gabsprates** [raisiqueira/raisiqueira.me#302]
Hey!

I was reading your post about tree shaking (very nice, by the way), and I found a bit of difficult to clearly see and read the code on code snippets.

![image](https://user-images.githubusercontent.com/12635603/84401253-70fb6d00-abd9-11ea-9705-ca5ac5c08b05.png)

I don't know, maybe if you use a more contrast colors to highlight the code it'll be better to see/read.

Again, good post! :wink:

**Comment by raisiqueira** [comment]
@gabsprates Thanks for feedback. I'll make a improvement on code blocks 😁
